### ISSUE TITLE
Ship a Kiba cookbook

### ISSUE THREAD

**Issue by thbar** [thbar/kiba#29]
While working on consulting doing ETL (either Kiba-based or not) in the past 6 months, I've gathered common topics of interests.

I'm in the process of writing a cookbook (free to read online, paid to get a PDF version or show support).

This issue will track progress with regard to the cookbook.
## Current outline

Not ordered by section nor by priority at this point and more of a brain-dump:
- [ ] how-to-add-assertions-to-your-etl.md
- [ ] how-to-add-continuous-integration-testing.md
- [ ] how-to-add-external-monitoring-to-your-etl.md
- [ ] how-to-add-logging.md
- [ ] how-to-add-metrics-to-your-etl.md
- [ ] how-to-avoid-concurrent-etl-processes.md
- [ ] how-to-build-an-incremental-etl.md
- [ ] how-to-create-tables-on-the-fly.md
- [ ] how-to-get-errors-on-bad-exit.md
- [ ] how-to-iterate-quickly-on-etl-code.md
- [ ] how-to-join-2-sql-tables.md
- [ ] how-to-make-transforms-more-reusable.md
- [ ] how-to-pass-parameters-to-the-etl.md
- [ ] how-to-profile-your-data.md (see #22)
- [ ] how-to-save-your-eyes.md
- [ ] how-to-send-an-email-report.md
- [ ] how-to-sequence-multiple-kiba-scripts.md (see #26)
- [ ] how-to-setup-end-to-end-etl-testing-with-mocks-and-env.md
- [ ] how-to-structure-dsl-extensions.md
- [ ] how-to-structure-your-etl-common-code.md (see #11)
- [ ] how-to-unit-test-your-components.md
- [ ] how-to-work-on-a-subset-of-your-data.md
## Remaining steps
- [x] Find a writing platform (now using [GitBook](https://www.gitbook.com/))
- [ ] Sort out legal & finance bits
- [ ] Find a way to sell it with limited overhead for me (as a EU, VAT-enabled seller)
- [ ] Publish first 3 chapters
- [ ] Structure the rest of the book

**Comment by zdrummond** [comment]
Any progress on this?

**Comment by thbar** [comment]
@zdrummond not at this point, unfortunately! I emailed you to see if I can help, though.

**Comment by thbar** [comment]
Closing for now due to excess of work-load. I'll definitely come back to this later, though.

**Comment by danbartlett** [comment]
I would love to read anything on How to Unit Test your Components. I'm trying to test some of my kiba destinations, but I cannot get rspec-rails to load the files correctly. Are there any examples of this? I've looked over the wiki, closed issues and stackoverflow.

**Comment by pmackay** [comment]
@thbar did you create a repo or starting point for this cookbook?

**Comment by thbar** [comment]
@pmackay not yet ; I have not completely eliminated the idea of doing this, but I'll first have to ship Kiba Pro & also a contributor agreement (which will come soon).

That said I would love to hear about your expectations on this topic, and your feedback could definitely have an impact on what.

Can you send me a more detailed note at thibaut.barrere+kiba@gmail.com with more details on what you expect?

Many thanks!

**Comment by brandonzylstra** [comment]
any word on when this is coming?

**Comment by thbar** [comment]
HI @brandondrew! Sadly I had to dismiss the idea for now, such a work is not sustainable (at least at the moment) for me.
